gpu: 0
seed: 99

timeloop:

  # Model Params
  model_type : people_snapshot
  num_epochs : 2500
  device : cuda:0
  start_frame : 25
  end_frame : 275
  skip_frames : 10
  warm_ups : 300
  warm_ups_remesh : 400
  remesh_freq : 300
  batch_size : 1
  model : general
  skinning_func : rbf  
  stop_train_after_warmup : True
  use_grad_clipping : False
  retriangulate: 0
  remeshing : False
  create_new_optimizer : True
  gradient_clipping : True
  noise_level : 0.001
  vertex_noise : False
  use_dynamic_texture : False
  remesh_percentile : 0.9
  texture_recon : False

  # Save Paths
  output_path: /hdd_data/nakul/soham/Resulrs_monorecon/LongTshirt
  Exp_name : Baseline

  # Input Paths
  smpl_path : /home/nakul/soham/3d/fixnormalndepth/basicmodel_m_lbs_10_207_0_v1.0.0.pkl
  smpl_pkl : /hdd_data/nakul/soham/Dataset/People_Snapshot/female-1-casual/4dhumans/output_data.pkl
  mesh: /hdd_data/nakul/soham/Template_dir/full_shirt/fullsleeve_tshirt.obj
  target_diffuse_maps : /hdd_data/nakul/soham/Dataset/People_Snapshot/female-1-casual/images_diffuse_1b_upper
  target_shil_maps : /hdd_data/nakul/soham/Dataset/People_Snapshot/female-1-casual/images_shils_1b_upper
  target_complete_shil_maps : /hdd_data/nakul/soham/Dataset/People_Snapshot/female-1-casual/seg_human_mask
  target_normal : /hdd_data/nakul/soham/Dataset/People_Snapshot/female-1-casual/norm_seg
  target_images : /hdd_data/nakul/soham/Dataset/People_Snapshot/female-1-casual/images_diffuse_1b_upper
  image_size : 1080   

  # Training Parameters
  position_lr_init : 0.0003 
  position_lr_final : 0.0000016
  position_lr_delay_mult : 0.01
  position_lr_max_steps : 25_000
  deform_lr_max_steps : 35_000
  custom_training_cannonical : True

  # Losses
  losses:
    RenderingLoss: 5.0
    Regularization: 0.0
    StVKLoss: 1.0
    BendingLoss: 1.0  

  #Logging
  logging : False
  log_interval: 5
  log_interval_im: 150
  log_elev: 0
  log_fov: 60.0
  log_dist: 3.0
  log_res: 512
  log_light_power: 3.0

  ## Texture
  texture_map : [1024,1024]
  max_mip_level : 3
  lr_base : 0.02
  tex_epochs : 1000
  texture_warm_ups : 10000
  use_dynamic_texture : False