gpu: 0
seed: 99

timeloop:

  # Model Params
  model_type : Synthetic
  num_epochs : 2500
  device : cuda:0
  start_frame : 25
  end_frame : 275
  skip_frames : 10
  warm_ups : 300
  warm_ups_remesh : 500
  remesh_freq : 200
  batch_size : 1
  model : general
  skinning_func : rbf  
  stop_train_after_warmup : True
  use_grad_clipping : False
  retriangulate: 0
  remeshing : True
  create_new_optimizer : True
  gradient_clipping : True
  noise_level : 0.001
  vertex_noise : True
  use_dynamic_texture : False
  remesh_percentile : 0.9
  hidden_layers : 3
  pose_noise : False
  max_verts : 15_000
  start_edge_len : 0.03
  end_edge_len : 0.007
  start_percentile : 0.65
  end_percentile : 0.9
  remesh_stop : 1500
  
  # Save Paths
  output_path: /hdd_data/nakul/soham/Resulrs_monorecon/Shorts/RemainingDebug
  Exp_name : Remeshing
  save_instance : True
  save_index : 35

  # Input Paths
  smpl_path : /home/nakul/soham/3d/fixnormalndepth/basicmodel_m_lbs_10_207_0_v1.0.0.pkl
  smpl_pkl : /hdd_data/nakul/soham/Dataset/People_Snapshot/male-4-sport/4dhumans/output_data.pkl
  mesh: /hdd_data/nakul/soham/Template_dir/shorts_smooth/smooth_shorts.obj
  target_diffuse_maps : /hdd_data/nakul/soham/Dataset/male-4-sport/images_diffuse_1b
  target_shil_maps : /hdd_data/nakul/soham/Dataset/male-4-sport/images_shils_1b
  target_complete_shil_maps : /hdd_data/nakul/soham/Dataset/male-4-sport/images_shils_human_1b
  target_hand_mask : /hdd_data/nakul/soham/Dataset/People_Snapshot/male-4-sport/hands_mask
  target_normal : /hdd_data/nakul/soham/Dataset/People_Snapshot/male-4-sport/norm_seg
  target_images : /hdd_data/nakul/soham/Dataset/People_Snapshot/male-4-sport/seg_shorts
  image_size : 1080   

  # Training Parameters
  position_lr_init : 0.0003 
  position_lr_final : 0.00001
  position_lr_delay_mult : 0.01
  position_lr_max_steps : 25_000
  deform_lr_max_steps : 35_000
  custom_training_cannonical : True

  # Losses
  losses:
    RenderingLoss: 5.0
    Regularization: 0.0
    StVKLoss: 1.0
    BendingLoss: 1.0  

  #Logging
  logging : False
  log_interval: 5
  log_interval_im: 150
  log_elev: 0
  log_fov: 60.0
  log_dist: 3.0
  log_res: 512
  log_light_power: 3.0

  ## Texture
   ## Texture
  texture_recon : False
  texture_lr_base : 0.02
  texture_lr_base_dyn : 0.002
  texture_map : [1024,1024]
  max_mip_level : 3
  tex_epochs : 100
  texture_warm_ups : 1
  use_dynamic_texture : False
  texture_lr_init : 0.03 
  texture_lr_final : 0.000016
  texture_lr_delay_mult : 0.01
  texture_lr_max_steps : 30000
  spatial_lr_scale : 5
  ssim_coeff : 0.35
  # texture_lr_max_steps : 30_000